import type { SeedProfile } from "./types";

export const SEED_PROFILES: SeedProfile[] = [
  {
    id: "p001",
    nombre: "Valentina Ospina",
    edad: 23,
    ocupacion: "Estudiante de Diseño",
    barrio: "Granada",
    foto: "https://i.pravatar.cc/150?img=5",
    descripcion:
      "Tranquila y ordenada. Paso las noches dibujando o leyendo, no en rumbas. Busco alguien que respete los espacios compartidos.",
    presupuesto: "600-900",
    zona: "sur",
    limpieza: "ordenado",
    horario: "maananero",
    ruido: "silencio",
    visitas: "casi-nunca",
    mascotas: "acepto",
    fumar: "no-fumo",
    fecha: "2-4-semanas",
    cocina: "todos-dias",
    fiestas: "nunca",
    genero: "solo-mujeres",
    pareja: "respeto",
    gastos: "50-50",
    dealbreakers: ["desorden-extremo", "visitas-sin-avisar"],
  },
  {
    id: "p002",
    nombre: "Julián Morales",
    edad: 24,
    ocupacion: "Desarrollador backend",
    barrio: "El Peñón",
    foto: "https://i.pravatar.cc/150?img=12",
    descripcion:
      "Trabajo desde casa y salgo poco. Me adapto bien a distintos estilos siempre que haya respeto. Fan del silencio para concentrarme.",
    presupuesto: "600-900",
    zona: "me-adapto",
    limpieza: "ordenado",
    horario: "noctambulo",
    ruido: "normal",
    visitas: "1-2-semana",
    mascotas: "acepto",
    fumar: "no-fumo",
    fecha: "2-4-semanas",
    cocina: "ocasional",
    fiestas: "ocasional",
    genero: "mixto",
    pareja: "ok",
    gastos: "flexible",
    dealbreakers: [],
  },
  {
    id: "p003",
    nombre: "Isabella Cruz",
    edad: 24,
    ocupacion: "Contadora",
    barrio: "San Fernando",
    foto: "https://i.pravatar.cc/150?img=9",
    descripcion:
      "Muy organizada, la cocina y los espacios comunes siempre limpios. Trabajo en horario fijo, llego puntual y no armo desorden.",
    presupuesto: "600-900",
    zona: "sur",
    limpieza: "ordenado",
    horario: "maananero",
    ruido: "silencio",
    visitas: "casi-nunca",
    mascotas: "no-quiero",
    fumar: "no-fumo",
    fecha: "2-4-semanas",
    cocina: "todos-dias",
    fiestas: "nunca",
    genero: "sin-preferencia",
    pareja: "respeto",
    gastos: "50-50",
    dealbreakers: ["desorden-extremo"],
  },
  {
    id: "p004",
    nombre: "Sebastián Muñoz",
    edad: 27,
    ocupacion: "Diseñador freelance",
    barrio: "San Antonio",
    foto: "https://i.pravatar.cc/150?img=15",
    descripcion:
      "Creativo y adaptable. Tengo horario irregular pero soy respetuoso. Me gusta la música pero no a alto volumen después de las 10.",
    presupuesto: "600-900",
    zona: "centro",
    limpieza: "relajado",
    horario: "noctambulo",
    ruido: "normal",
    visitas: "1-2-semana",
    mascotas: "acepto",
    fumar: "no-fumo",
    fecha: "explorando",
    cocina: "ocasional",
    fiestas: "ocasional",
    genero: "mixto",
    pareja: "ok",
    gastos: "flexible",
    dealbreakers: [],
  },
  {
    id: "p005",
    nombre: "Daniela Reyes",
    edad: 25,
    ocupacion: "Ingeniera de sistemas",
    barrio: "Chipichape",
    foto: "https://i.pravatar.cc/150?img=14",
    descripcion:
      "Muy seria con el orden y los tiempos. Salgo temprano, vuelvo a las 6pm y no me gustan las sorpresas. Busco convivencia tranquila y predecible.",
    presupuesto: "900-1200",
    zona: "norte",
    limpieza: "obsesivo",
    horario: "madrugador",
    ruido: "silencio",
    visitas: "casi-nunca",
    mascotas: "no-quiero",
    fumar: "no-fumo",
    fecha: "ya",
    cocina: "todos-dias",
    fiestas: "nunca",
    genero: "sin-preferencia",
    pareja: "prefiero-no",
    gastos: "coordinador",
    dealbreakers: ["visitas-sin-avisar", "fumar-cerrado", "desorden-extremo"],
  },
  {
    id: "p006",
    nombre: "Laura Mendoza",
    edad: 27,
    ocupacion: "Comunicadora social",
    barrio: "Centenario",
    foto: "https://i.pravatar.cc/150?img=16",
    descripcion:
      "Sociable pero respetuosa. Me adapto a distintas zonas y estilos. Trabajo en medios, tengo horario variable pero aviso siempre.",
    presupuesto: "600-900",
    zona: "me-adapto",
    limpieza: "ordenado",
    horario: "variable",
    ruido: "normal",
    visitas: "1-2-semana",
    mascotas: "acepto",
    fumar: "no-fumo",
    fecha: "2-4-semanas",
    cocina: "ocasional",
    fiestas: "nunca",
    genero: "sin-preferencia",
    pareja: "ok",
    gastos: "flexible",
    dealbreakers: ["visitas-sin-avisar"],
  },
  {
    id: "p007",
    nombre: "Felipe Castillo",
    edad: 30,
    ocupacion: "Trabajador remoto (UX)",
    barrio: "Ciudad Jardín",
    foto: "https://i.pravatar.cc/150?img=33",
    descripcion:
      "Home office toda la semana. Tengo un gato muy tranquilo llamado Mango. Soy ordenado y callado, pero el gato manda en el apartamento.",
    presupuesto: "900-1200",
    zona: "sur",
    limpieza: "relajado",
    horario: "variable",
    ruido: "normal",
    visitas: "1-2-semana",
    mascotas: "tengo",
    fumar: "no-fumo",
    fecha: "2-4-semanas",
    cocina: "casi-no",
    fiestas: "ocasional",
    genero: "sin-preferencia",
    pareja: "ok",
    gastos: "flexible",
    dealbreakers: [],
  },
  {
    id: "p008",
    nombre: "María José Herrera",
    edad: 22,
    ocupacion: "Estudiante de Medicina",
    barrio: "Versalles",
    foto: "https://i.pravatar.cc/150?img=21",
    descripcion:
      "Estudio medicina, tengo horarios imposibles. Necesito silencio total para estudiar. No fumo ni acepto fumadores. Super limpia.",
    presupuesto: "menos-600",
    zona: "norte",
    limpieza: "obsesivo",
    horario: "madrugador",
    ruido: "silencio",
    visitas: "casi-nunca",
    mascotas: "no-quiero",
    fumar: "no-fumo",
    fecha: "ya",
    cocina: "todos-dias",
    fiestas: "nunca",
    genero: "solo-mujeres",
    pareja: "prefiero-no",
    gastos: "50-50",
    dealbreakers: ["fumar-cerrado", "desorden-extremo", "visitas-sin-avisar"],
  },
  {
    id: "p009",
    nombre: "Andrés Bermúdez",
    edad: 32,
    ocupacion: "Abogado",
    barrio: "Granada",
    foto: "https://i.pravatar.cc/150?img=57",
    descripcion:
      "Muy ordenado y privado. Llego tarde del trabajo pero no hago ruido. Pago puntual. Busco convivencia sin drama ni visitas constantes.",
    presupuesto: "mas-1200",
    zona: "sur",
    limpieza: "obsesivo",
    horario: "noctambulo",
    ruido: "silencio",
    visitas: "casi-nunca",
    mascotas: "no-quiero",
    fumar: "no-fumo",
    fecha: "1-2-meses",
    cocina: "casi-no",
    fiestas: "nunca",
    genero: "solo-hombres",
    pareja: "prefiero-no",
    gastos: "coordinador",
    dealbreakers: ["desorden-extremo", "visitas-sin-avisar"],
  },
  {
    id: "p010",
    nombre: "Natalia López",
    edad: 21,
    ocupacion: "Estudiante de Medicina",
    barrio: "Normandía",
    foto: "https://i.pravatar.cc/150?img=25",
    descripcion:
      "Primera vez viviendo sola. Soy muy limpia, madrugadora y callada. Busco ambiente tranquilo cerca de la universidad del norte.",
    presupuesto: "menos-600",
    zona: "norte",
    limpieza: "ordenado",
    horario: "madrugador",
    ruido: "silencio",
    visitas: "casi-nunca",
    mascotas: "no-quiero",
    fumar: "no-fumo",
    fecha: "ya",
    cocina: "todos-dias",
    fiestas: "nunca",
    genero: "solo-mujeres",
    pareja: "prefiero-no",
    gastos: "50-50",
    dealbreakers: ["fumar-cerrado"],
  },
  {
    id: "p011",
    nombre: "Tomás Guerrero",
    edad: 29,
    ocupacion: "Fotógrafo",
    barrio: "San Antonio",
    foto: "https://i.pravatar.cc/150?img=61",
    descripcion:
      "Trabajo de noche y duermo de día. Hay mucho movimiento en mi vida. Si eres de las 6am y silencio total, probablemente no somos compatibles.",
    presupuesto: "600-900",
    zona: "centro",
    limpieza: "relajado",
    horario: "noctambulo",
    ruido: "ocasional",
    visitas: "casi-siempre",
    mascotas: "acepto",
    fumar: "afuera",
    fecha: "explorando",
    cocina: "casi-no",
    fiestas: "frecuente",
    genero: "mixto",
    pareja: "ok",
    gastos: "acordamos",
    dealbreakers: [],
  },
  {
    id: "p012",
    nombre: "Mateo García",
    edad: 26,
    ocupacion: "Profesor de secundaria",
    barrio: "Centenario",
    foto: "https://i.pravatar.cc/150?img=3",
    descripcion:
      "Tranquilo, mañanero, me gusta cocinar y tener la cocina organizada. Salgo a caminar los fines de semana. Convivencia sin complicaciones.",
    presupuesto: "600-900",
    zona: "norte",
    limpieza: "ordenado",
    horario: "maananero",
    ruido: "normal",
    visitas: "1-2-semana",
    mascotas: "acepto",
    fumar: "no-fumo",
    fecha: "2-4-semanas",
    cocina: "todos-dias",
    fiestas: "nunca",
    genero: "mixto",
    pareja: "ok",
    gastos: "acordamos",
    dealbreakers: [],
  },
  {
    id: "p013",
    nombre: "Paola Jiménez",
    edad: 31,
    ocupacion: "Emprendedora (ropa sostenible)",
    barrio: "Menga",
    foto: "https://i.pravatar.cc/150?img=36",
    descripcion:
      "Emprendedora con clientes en casa a veces. Soy flexible con los espacios y prefiero llegar a acuerdos sobre la marcha. Amo los perros.",
    presupuesto: "900-1200",
    zona: "norte",
    limpieza: "relajado",
    horario: "variable",
    ruido: "normal",
    visitas: "casi-siempre",
    mascotas: "tengo",
    fumar: "indiferente",
    fecha: "2-4-semanas",
    cocina: "casi-no",
    fiestas: "ocasional",
    genero: "sin-preferencia",
    pareja: "ok",
    gastos: "flexible",
    dealbreakers: [],
  },
  {
    id: "p014",
    nombre: "Ricardo Salazar",
    edad: 23,
    ocupacion: "Estudiante de Economía",
    barrio: "Chipichape",
    foto: "https://i.pravatar.cc/150?img=7",
    descripcion:
      "Estudiante con beca, muy juicioso pero también me gusta socializar los fines de semana. No soy el más ordenado del mundo, lo admito.",
    presupuesto: "menos-600",
    zona: "norte",
    limpieza: "relajado",
    horario: "noctambulo",
    ruido: "ocasional",
    visitas: "1-2-semana",
    mascotas: "acepto",
    fumar: "no-fumo",
    fecha: "explorando",
    cocina: "casi-no",
    fiestas: "frecuente",
    genero: "mixto",
    pareja: "depende",
    gastos: "acordamos",
    dealbreakers: [],
  },
  {
    id: "p015",
    nombre: "Sara Quintero",
    edad: 28,
    ocupacion: "Nutricionista",
    barrio: "San Fernando",
    foto: "https://i.pravatar.cc/150?img=44",
    descripcion:
      "Cocino todos los días y espero lo mismo de quien comparta el espacio. La cocina limpia no es negociable. Madrugadora y muy organizada.",
    presupuesto: "900-1200",
    zona: "sur",
    limpieza: "obsesivo",
    horario: "madrugador",
    ruido: "silencio",
    visitas: "casi-nunca",
    mascotas: "no-quiero",
    fumar: "no-fumo",
    fecha: "1-2-meses",
    cocina: "todos-dias",
    fiestas: "nunca",
    genero: "solo-mujeres",
    pareja: "respeto",
    gastos: "50-50",
    dealbreakers: ["desorden-extremo", "visitas-sin-avisar", "fumar-cerrado"],
  },
  {
    id: "p016",
    nombre: "Esteban Córdoba",
    edad: 34,
    ocupacion: "Chef",
    barrio: "El Peñón",
    foto: "https://i.pravatar.cc/150?img=70",
    descripcion:
      "Chef de restaurante. Llego tarde, traigo gente a casa, fumo en el balcón. Busco convivencia sin reglas exageradas. Me gusta vivir bien.",
    presupuesto: "mas-1200",
    zona: "sur",
    limpieza: "caos",
    horario: "noctambulo",
    ruido: "mucho",
    visitas: "casa-abierta",
    mascotas: "acepto",
    fumar: "afuera",
    fecha: "2-4-semanas",
    cocina: "todos-dias",
    fiestas: "estilo-vida",
    genero: "mixto",
    pareja: "ok",
    gastos: "coordinador",
    dealbreakers: [],
  },
  {
    id: "p017",
    nombre: "Sofía Ramírez",
    edad: 20,
    ocupacion: "Estudiante de Artes",
    barrio: "San Antonio",
    foto: "https://i.pravatar.cc/150?img=47",
    descripcion:
      "Artista, noctámbula, creativa. Me importa más la energía del espacio que el orden perfecto. Busco roomies chill, no inspectores de limpieza.",
    presupuesto: "600-900",
    zona: "centro",
    limpieza: "relajado",
    horario: "noctambulo",
    ruido: "normal",
    visitas: "casi-nunca",
    mascotas: "no-quiero",
    fumar: "no-fumo",
    fecha: "ya",
    cocina: "casi-no",
    fiestas: "ocasional",
    genero: "solo-mujeres",
    pareja: "respeto",
    gastos: "50-50",
    dealbreakers: [],
  },
  {
    id: "p018",
    nombre: "Carlos Patiño",
    edad: 38,
    ocupacion: "Ingeniero senior (remoto)",
    barrio: "Ciudad Jardín",
    foto: "https://i.pravatar.cc/150?img=11",
    descripcion:
      "Muy serio con el orden. Trabajo desde casa en silencio total. No acepto ruido ni visitas frecuentes. Pago sin excusas el día 1.",
    presupuesto: "mas-1200",
    zona: "sur",
    limpieza: "obsesivo",
    horario: "madrugador",
    ruido: "silencio",
    visitas: "casi-nunca",
    mascotas: "no-quiero",
    fumar: "no-fumo",
    fecha: "1-2-meses",
    cocina: "todos-dias",
    fiestas: "nunca",
    genero: "sin-preferencia",
    pareja: "prefiero-no",
    gastos: "50-50",
    dealbreakers: ["desorden-extremo", "visitas-sin-avisar", "fumar-cerrado"],
  },
  {
    id: "p019",
    nombre: "Andrea Salcedo",
    edad: 29,
    ocupacion: "Psicóloga",
    barrio: "Tequendama",
    foto: "https://i.pravatar.cc/150?img=32",
    descripcion:
      "Empática y tranquila. Me adapto bien pero necesito mis espacios de silencio al llegar del trabajo. Los conflictos me los dices de frente.",
    presupuesto: "600-900",
    zona: "sur",
    limpieza: "ordenado",
    horario: "maananero",
    ruido: "normal",
    visitas: "1-2-semana",
    mascotas: "acepto",
    fumar: "no-fumo",
    fecha: "2-4-semanas",
    cocina: "ocasional",
    fiestas: "nunca",
    genero: "sin-preferencia",
    pareja: "respeto",
    gastos: "flexible",
    dealbreakers: ["fumar-cerrado"],
  },
  {
    id: "p020",
    nombre: "David Peña",
    edad: 35,
    ocupacion: "Arquitecto",
    barrio: "Santa Mónica",
    foto: "https://i.pravatar.cc/150?img=1",
    descripcion:
      "Metódico y detallista. Necesito el apartamento en orden para pensar bien. Suelo trabajar hasta tarde pero sin armar bulla. Buen roomie.",
    presupuesto: "900-1200",
    zona: "norte",
    limpieza: "obsesivo",
    horario: "noctambulo",
    ruido: "silencio",
    visitas: "casi-nunca",
    mascotas: "alergico",
    fumar: "no-fumo",
    fecha: "1-2-meses",
    cocina: "ocasional",
    fiestas: "nunca",
    genero: "mixto",
    pareja: "depende",
    gastos: "50-50",
    dealbreakers: ["animales", "desorden-extremo"],
  },
];
